(()=>{
const API=window.VELTO_API_URL;
const token=()=>localStorage.getItem("velto_token")||"";
const H=()=>token()?{Authorization:`Bearer ${token()}`}:{ };
const J=async r=>{try{return await r.json()}catch{return{}}};
let user=null,offerTimer=null,offerIds=new Set(),lastOffersSignature="",lastDriverSignature="",lastDriverFilter="",driverRequestInFlight=false,offersRequestInFlight=false;
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const typeInfo={colis:["📦","Colis"],food:["🍔","Food"],taxi:["🚗","Taxi"],shop:["🛍️","Shop"],market:["🛒","Market"]};
function typeOf(o){if(o.serviceType&&typeInfo[o.serviceType])return o.serviceType;const m=String(o.pkg||"").match(/^\[(COLIS|FOOD|TAXI|SHOP|MARKET)\]/i);return m?m[1].toLowerCase():"colis"}
function toast(m){let x=$("#d2toast");if(!x){x=document.createElement("div");x.id="d2toast";x.style="position:fixed;right:20px;bottom:20px;z-index:100000;background:#211d18;color:#fff;padding:13px 17px;border-radius:13px;font:600 13px Inter,Arial;box-shadow:0 12px 35px rgba(0,0,0,.2)";document.body.append(x)}x.textContent=m;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),3200)}
function notify(m){if("Notification" in window&&Notification.permission==="granted")new Notification("Velto — nouvelle course",{body:m});}
function styles(){if($("#d2style"))return;const s=document.createElement("style");s.id="d2style";s.textContent=`.d2grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:15px 0}.d2stat{padding:15px;border:1px solid rgba(36,28,16,.1);border-radius:15px;background:rgba(255,255,255,.35)}.d2stat small{color:#857a67}.d2stat b{display:block;font-size:23px;margin-top:5px}.d2tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.d2btn{padding:10px 14px;border-radius:11px;border:1px solid #ddd;background:white;font-weight:700;cursor:pointer}.d2primary{background:#211d18;color:white}.d2row{display:flex;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid #eee}.d2type{display:inline-flex;align-items:center;gap:5px;padding:4px 8px;border-radius:99px;background:#f3eee6;font-size:12px;font-weight:700}.d2distance{display:inline-block;margin-left:7px;font-weight:700;color:#6e6250}.d2filter{padding:8px 11px;border:1px solid #ddd;border-radius:10px;background:white;font-weight:700;cursor:pointer}.d2filter.active{background:#211d18;color:#fff}.d2map{height:250px;border-radius:15px;overflow:hidden}.d2offers{margin:15px 0;padding:16px;border-radius:18px;border:1px solid rgba(214,178,94,.35);background:linear-gradient(135deg,rgba(255,255,255,.75),rgba(246,238,220,.7));box-shadow:0 12px 35px rgba(33,29,24,.08)}.d2offer{padding:15px;margin-top:10px;border-radius:15px;background:#fff;border:1px solid #eee;box-shadow:0 8px 25px rgba(0,0,0,.06)}.d2offer:first-child{margin-top:0}.d2offerhead{display:flex;justify-content:space-between;align-items:center;gap:10px}.d2countdown{font-weight:900;min-width:58px;text-align:center;padding:7px 9px;border-radius:10px;background:#211d18;color:#fff}.d2offerroute{margin:10px 0;line-height:1.55}.d2offeractions{display:flex;gap:8px}.d2offeractions button{flex:1}.d2empty{color:#857a67;font-size:13px;margin:7px 0 0}@media(max-width:800px){.d2grid{grid-template-columns:repeat(2,1fr)}.d2row{flex-direction:column}.d2offerhead{align-items:flex-start}.d2offeractions{flex-direction:column}}`;document.head.append(s)}
async function me(){const t=token();if(!t)return;const r=await fetch(API+"/auth/me",{headers:H()}).catch(()=>null);if(r?.ok)user=(await J(r)).user}
async function driver(){const v=$("#view-livreur");if(!v||$("#d2driver"))return;const b=document.createElement("div");b.id="d2driver";b.className="glass-panel";b.innerHTML=`<h1>Tableau de bord livreur</h1><p class="subtitle">Gérez vos courses, votre disponibilité et votre position GPS.</p><div class="d2grid"><div class="d2stat"><small>Gains</small><b id="d2earn">0 DT</b></div><div class="d2stat"><small>Livraisons</small><b id="d2done">0</b></div><div class="d2stat"><small>Commandes actives</small><b id="d2activeCount">0</b></div><div class="d2stat"><small>GPS</small><b id="d2gps">Off</b></div></div><div class="d2tools"><button id="d2online" class="d2btn d2primary"></button><button id="d2gpsbtn" class="d2btn">Activer GPS</button></div><div class="d2tools" id="d2capabilities"><b>Services acceptés :</b>${["colis","food","shop","market"].map(x=>`<label class="d2type"><input type="checkbox" data-capability="${x}" ${user?.capabilities?.includes(x)?"checked":""}> ${x}</label>`).join("")}<button id="d2savecaps" class="d2btn">Enregistrer</button></div><section id="d2offers" class="d2offers"><div class="d2offerhead"><h2 style="margin:0">🔔 Nouvelles courses</h2><span id="d2offerCount" class="d2type">0</span></div><div id="d2offerList"><p class="d2empty">Activez votre statut en ligne pour recevoir des courses.</p></div></section><div class="d2tools" id="d2filters"><button class="d2filter active" data-f="all">Toutes</button><button class="d2filter" data-f="colis">📦 Colis</button><button class="d2filter" data-f="food">🍔 Food</button><button class="d2filter" data-f="taxi">🚗 Taxi</button><button class="d2filter" data-f="shop">🛍️ Shop</button><button class="d2filter" data-f="market">🛒 Market</button></div><div class="d2row"><div style="flex:1"><h2>Courses disponibles</h2><div id="d2available">Aucune nouvelle course.</div><h2 style="margin-top:22px">Course active</h2><div id="d2active">Aucune course active.</div></div><div style="width:42%"><h2>Position</h2><div id="d2map" class="d2map"></div></div></div><h2 style="margin-top:22px">Historique des courses</h2><div id="d2history"></div>`;v.prepend(b);
$("#d2online").onclick=async()=>{const on=!user?.isOnline;const r=await fetch(API+"/drivers/me/status",{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({isOnline:on,isAvailable:on})});const d=await J(r);if(r.ok){user=d.user||user;renderOnline();toast(on?"Vous êtes en ligne":"Vous êtes hors ligne");if(on)pollOffers();else clearOfferPolling()}else toast(d.error||"Erreur")};
$("#d2gpsbtn").onclick=startGPS;
$("#d2savecaps").onclick=async()=>{const capabilities=[...document.querySelectorAll("[data-capability]:checked")].map(x=>x.dataset.capability);if(!capabilities.length)return toast("Sélectionnez au moins un service");const r=await fetch(API+"/drivers/me/capabilities",{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({capabilities})});const d=await J(r);if(r.ok){user.capabilities=d.capabilities||capabilities;toast("Services enregistrés")}else toast(d.error||"Erreur d'enregistrement")};
$("#d2filters").onclick=e=>{const btn=e.target.closest("[data-f]");if(!btn)return;document.querySelectorAll("#d2filters .d2filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");loadDriver(btn.dataset.f)};
if("Notification" in window&&Notification.permission==="default")Notification.requestPermission().catch(()=>{});
renderOnline();loadDriver("all");pollOffers();setInterval(()=>loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all"),5000)}
function renderOnline(){if($("#d2online"))$("#d2online").textContent=user?.isOnline?"Passer hors ligne":"Passer en ligne"}
function clearOfferPolling(){if(offerTimer){clearInterval(offerTimer);offerTimer=null}offerIds.clear();lastOffersSignature="";renderOffers([])}
function pollOffers(){if(user?.role!=="livreur")return;loadOffers();if(!offerTimer)offerTimer=setInterval(loadOffers,2500)}
async function loadOffers(){if(offersRequestInFlight||user?.role!=="livreur"||!user?.isOnline){if(!user?.isOnline)renderOffers([]);return}offersRequestInFlight=true;try{const r=await fetch(API+"/drivers/me/offers",{headers:H()}).catch(()=>null);if(!r?.ok)return;const data=await J(r);const offers=Array.isArray(data)?data:[];const fresh=new Set(offers.map(x=>String(x.order?.id||x.order?._id||"")));for(const x of offers){const id=String(x.order?.id||x.order?._id||"");if(id&&!offerIds.has(id)){offerIds.add(id);notify(`${typeInfo[typeOf(x.order)]?.[1]||"Course"} · ${x.offer?.distanceToPickupKm??"—"} km du retrait`);toast("🔔 Nouvelle course disponible")}}for(const id of [...offerIds])if(!fresh.has(id))offerIds.delete(id);const signature=offers.map(x=>`${x.order?.id||x.order?._id}:${x.offer?.expiresAt}:${x.offer?.status||"offered"}`).join("|");if(signature!==lastOffersSignature){lastOffersSignature=signature;renderOffers(offers)}}finally{offersRequestInFlight=false}}
function renderOffers(offers){const h=$("#d2offerList"),count=$("#d2offerCount");if(!h)return;count.textContent=String(offers.length);if(!offers.length){h.innerHTML='<p class="d2empty">Aucune offre en attente.</p>';return}h.innerHTML=offers.map(x=>{const o=x.order||{},of=x.offer||{},id=String(o.id||o._id||"");const exp=new Date(of.expiresAt).getTime();const sec=Math.max(0,Math.ceil((exp-Date.now())/1000));return `<article class="d2offer" data-offer-id="${esc(id)}"><div class="d2offerhead"><div>${badge(o)} <b>#${esc(id.slice(-5))}</b></div><span class="d2countdown" data-exp="${exp}">${sec}s</span></div><div class="d2offerroute"><b>📍 ${esc(o.pickup)}</b><br>↓<br><b>🏁 ${esc(o.dropoff)}</b></div><small>${esc(o.pkg)} · <b>${Number(o.fee||0).toFixed(2)} DT</b>${Number.isFinite(Number(of.distanceToPickupKm))?` · 📍 ${Number(of.distanceToPickupKm).toFixed(1)} km`:""}</small><div class="d2offeractions"><button class="d2btn d2primary" data-offer-action="accept" data-id="${esc(id)}">✓ Accepter</button><button class="d2btn" data-offer-action="decline" data-id="${esc(id)}">Refuser</button></div></article>`}).join("");h.onclick=e=>{const b=e.target.closest("[data-offer-action]");if(!b)return;b.disabled=true;b.dataset.offerAction==="accept"?acceptOffer(b.dataset.id,b):declineOffer(b.dataset.id,b)};h.querySelectorAll("[data-exp]").forEach(el=>{const tick=()=>{const sec=Math.max(0,Math.ceil((Number(el.dataset.exp)-Date.now())/1000));el.textContent=sec+"s";if(sec<=0){el.closest(".d2offer")?.remove();loadOffers()}};tick();const t=setInterval(()=>{if(!document.body.contains(el)){clearInterval(t);return}tick()},500)})}
async function acceptOffer(id,btn){const r=await fetch(API+`/orders/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({status:"acceptee"})});const d=await J(r);if(!r.ok){btn.disabled=false;return toast(d.error||"Offre déjà prise ou expirée")}toast("✓ Course acceptée");offerIds.delete(id);await loadOffers();loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all")}
async function declineOffer(id,btn){const r=await fetch(API+`/drivers/me/offers/${id}/decline`,{method:"POST",headers:H()});const d=await J(r);if(!r.ok){btn.disabled=false;return toast(d.error||"Offre expirée ou déjà prise")}offerIds.delete(id);toast("Offre refusée");loadOffers()}
async function loadDriver(filter="all"){if(driverRequestInFlight||user?.role!=="livreur")return;driverRequestInFlight=true;try{const r=await fetch(API+"/orders",{headers:H()});const os=await J(r);if(!Array.isArray(os))return;const signature=os.map(o=>`${o.id||o._id}:${o.status}:${o.updatedAt}`).join("|");if(signature===lastDriverSignature&&filter===lastDriverFilter)return;lastDriverSignature=signature;lastDriverFilter=filter;const done=os.filter(o=>o.status==="livree");$("#d2earn").textContent=done.reduce((n,o)=>n+Number(o.driverEarnings||0),0).toFixed(2)+" DT";$("#d2done").textContent=done.length;const active=os.filter(o=>["acceptee","route"].includes(o.status));$("#d2activeCount").textContent=active.length;const available=os.filter(o=>o.status==="nouvelle");renderAvailable(filter==="all"?available:available.filter(o=>typeOf(o)===filter));renderActive(active.filter(o=>filter==="all"||typeOf(o)===filter));const shown=filter==="all"?os:os.filter(o=>typeOf(o)===filter);renderHistory(shown.filter(o=>o.status==="livree"||o.status==="annulee"));}finally{driverRequestInFlight=false}}
function badge(o){const [i,n]=typeInfo[typeOf(o)]||typeInfo.colis;return `<span class="d2type">${i} ${n}</span>`}
function renderAvailable(list){const h=$("#d2available");if(!h)return;if(!list.length){h.innerHTML='<p class="empty-state">Aucune nouvelle course disponible.</p>';return}h.innerHTML=list.slice(0,20).map(a=>`<div style="padding-bottom:14px"><div>${badge(a)} <b>#${esc(String(a.id).slice(-5))}</b>${Number.isFinite(Number(a.distanceToPickupKm))?`<span class="d2distance">📍 ${Number(a.distanceToPickupKm).toFixed(1)} km</span>`:""}</div><p style="margin:9px 0">${esc(a.pickup)} → ${esc(a.dropoff)}</p><small>${esc(a.pkg)} · <b>${esc(window.VELTO_MONEY ? window.VELTO_MONEY(a.fee,a.currency||"USD") : `${Number(a.fee||0).toFixed(2)} ${a.currency||"USD"}`)}</b></small><div class="d2tools"><button class="d2btn d2primary" data-action="accept" data-id="${esc(a.id)}">Accepter la course</button></div></div>`).join("");h.onclick=e=>{const b=e.target.closest("[data-action]");if(b&&b.dataset.action==="accept")change(b.dataset.id,"acceptee")}}
function renderActive(active){const h=$("#d2active");if(!active.length){h.textContent="Aucune course active.";return}h.innerHTML=active.map(a=>`<div style="padding-bottom:14px"><div>${badge(a)} <b>#${esc(String(a.id).slice(-5))}</b></div><p style="margin:9px 0">${esc(a.pickup)} → ${esc(a.dropoff)}</p><small>${esc(a.pkg)} · <b>${Number(a.driverEarnings||0).toFixed(2)} DT</b></small><div class="d2tools"><button class="d2btn d2primary" data-action="${a.status==='acceptee'?'route':'livree'}" data-id="${esc(a.id)}">${a.status==='acceptee'?"En route":"Livré"}</button><button class="d2btn" data-action="cancel" data-id="${esc(a.id)}">Annuler</button></div></div>`).join("");h.onclick=e=>{const b=e.target.closest("[data-action]");if(b)b.dataset.action==="cancel"?cancel(b.dataset.id):change(b.dataset.id,b.dataset.action)} }
function renderHistory(list){const h=$("#d2history");if(!list.length){h.innerHTML='<p class="empty-state">Aucun historique pour ce filtre.</p>';return}h.innerHTML=list.slice(0,30).map(o=>`<div class="d2row"><span>${badge(o)} <b>#${esc(String(o.id).slice(-5))}</b><br><small>${esc(o.pickup)} → ${esc(o.dropoff)}</small></span><b>${esc(window.VELTO_MONEY ? window.VELTO_MONEY(o.driverEarnings,o.currency||"USD") : `${Number(o.driverEarnings||0).toFixed(2)} ${o.currency||"USD"}`)}</b></div>`).join("")}
async function change(id,status){const r=await fetch(API+`/orders/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({status})});const d=await J(r);if(!r.ok&&d.paymentAction==="cash-collected"){if(!confirm("Avez-vous bien encaissé le paiement cash ?"))return;const p=await fetch(API+`/payments/${id}`,{headers:H()}),pd=await J(p);if(!p.ok||!pd.payment)return toast(pd.error||"Paiement introuvable");const c=await fetch(API+`/payments/${pd.payment._id||pd.payment.id}/cash-collected`,{method:"POST",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({collected:true})}),cd=await J(c);if(!c.ok)return toast(cd.error||"Confirmation cash impossible");toast("Paiement cash confirmé")}else if(!r.ok)return toast(d.error||"Erreur");else toast(status==="acceptee"?"Course acceptée":status==="livree"?"Course livrée":"Course démarrée");loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all")}
async function cancel(id){const reason=prompt("Raison de l'annulation","Indisponible")||"Annulée par le livreur";const r=await fetch(API+`/orders/${id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({reason})});const d=await J(r);if(!r.ok)return toast(d.error||"Erreur");toast("Commande annulée");loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all")}
async function startGPS(){if(!navigator.geolocation)return toast("GPS non supporté");if(window.__veltoGpsWatch)return toast("GPS déjà actif");window.__veltoGpsWatch=navigator.geolocation.watchPosition(async p=>{const lat=p.coords.latitude,lng=p.coords.longitude;const r=await fetch(API+"/drivers/me/location",{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({lat,lng})});if(r.ok)$("#d2gps").textContent="Actif"},()=>toast("Autorisation GPS refusée"),{enableHighAccuracy:true,maximumAge:5000,timeout:10000});toast("GPS activé")}
async function admin(){if(user?.role!=="admin"||$("#d2admin"))return;const s=document.createElement("section");s.id="d2admin";s.className="view active";s.innerHTML=`<div class="glass-panel"><h1>Administration Velto</h1><div class="d2grid"><div class="d2stat"><small>Utilisateurs</small><b id="ausers">—</b></div><div class="d2stat"><small>Commandes</small><b id="aorders">—</b></div><div class="d2stat"><small>Livreurs en ligne</small><b id="aonline">—</b></div><div class="d2stat"><small>Commission</small><b id="acomm">—</b></div></div><div class="d2tools"><button class="d2filter active" data-af="all">Toutes</button><button class="d2filter" data-af="nouvelle">Nouvelles</button><button class="d2filter" data-af="acceptee">Acceptées</button><button class="d2filter" data-af="route">En route</button><button class="d2filter" data-af="livree">Livrées</button><button class="d2filter" data-af="annulee">Annulées</button></div><div id="alist"></div></div>`;$("main").append(s);s.onclick=e=>{const b=e.target.closest("[data-af]");if(!b)return;s.querySelectorAll("[data-af]").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadAdmin(b.dataset.af)};loadAdmin("all");setInterval(()=>loadAdmin(s.querySelector("[data-af].active")?.dataset.af||"all"),7000)}
async function loadAdmin(filter){if(user?.role!=="admin")return;const [a,b]=await Promise.all([fetch(API+"/admin/stats",{headers:H()}),fetch(API+"/orders",{headers:H()})]);const st=await J(a),os=await J(b);$("#ausers").textContent=st.users??st.totalUsers??"—";$("#aorders").textContent=st.orders??st.totalOrders??(Array.isArray(os)?os.length:"—");$("#aonline").textContent=st.onlineDrivers??st.onlineLivreurs??"—";$("#acomm").textContent=Number(st.commission??st.totalCommission??0).toFixed(2)+" DT";const list=Array.isArray(os)?(filter==="all"?os:os.filter(o=>o.status===filter)):[];$("#alist").innerHTML=list.slice(0,50).map(o=>`<div class="d2row"><span>${badge(o)} <b>#${esc(String(o.id).slice(-5))}</b><br>${esc(o.pickup)} → ${esc(o.dropoff)}<br><small>${esc(o.status)} · ${esc(o.pkg)}</small></span><b>${Number(o.fee||0).toFixed(2)} DT</b></div>`).join("")||'<p class="empty-state">Aucune commande.</p>'}
async function boot(){styles();await me();if(user?.role==="livreur")driver();if(user?.role==="admin")admin()}
boot();
})();