(() => {
  const API = "https://wassel-backend-ds3n.onrender.com";
  const state = { user: null, token: null, gpsWatch: null, lastOrderIds: new Set(), lastStatuses: new Map() };
  const $ = (s) => document.querySelector(s);
  const esc = (v) => String(v ?? "").replace(/[&<>\"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const headers = () => state.token ? { Authorization: `Bearer ${state.token}` } : {};
  const json = async (res) => { try { return await res.json(); } catch { return {}; } };
  const toast = (msg, ok = false) => { let h = $("#velto-dashboard-toast"); if (!h) { h = document.createElement("div"); h.id = "velto-dashboard-toast"; h.style.cssText = "position:fixed;right:20px;bottom:20px;z-index:100000;display:flex;flex-direction:column;gap:8px"; document.body.appendChild(h); } const x=document.createElement("div"); x.textContent=msg; x.style.cssText=`padding:12px 16px;border-radius:14px;background:#211d18;color:#fff;border:1px solid ${ok?"#d6b25e":"rgba(255,255,255,.12)"};font:600 13px Inter,Arial`; h.appendChild(x); setTimeout(()=>x.remove(),3500); };
  async function me() { state.token=localStorage.getItem("velto_token"); if(!state.token)return null; const r=await fetch(`${API}/auth/me`,{headers:headers()}).catch(()=>null); if(!r||!r.ok)return null; const d=await json(r); return d.user||null; }
  function css() { if($("#velto-dashboard-style"))return; const s=document.createElement("style");s.id="velto-dashboard-style";s.textContent=`.vd-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.vd-stat{padding:16px;border:1px solid rgba(36,28,16,.09);border-radius:16px;background:rgba(255,255,255,.45)}.vd-stat b{display:block;font:800 25px Sora,Arial;margin-top:5px}.vd-stat span{font-size:12px;color:#857a67}.vd-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.vd-btn{border:1px solid rgba(36,28,16,.12);border-radius:12px;padding:10px 13px;background:white;cursor:pointer;font-weight:700}.vd-btn.active,.vd-btn.accent{background:#211d18;color:#fff}.vd-status{font-size:12px;font-weight:700;padding:5px 9px;border-radius:999px;background:rgba(214,178,94,.18)}.vd-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:13px 0;border-bottom:1px solid rgba(36,28,16,.08)}.vd-row:last-child{border-bottom:0}.vd-muted{color:#857a67;font-size:12px}.vd-map{height:260px;border-radius:16px;overflow:hidden;margin-top:12px}.vd-two{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}@media(max-width:800px){.vd-grid{grid-template-columns:repeat(2,1fr)}.vd-two{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function ensureDriverUI(){ const view=$("#view-livreur"); if(!view||$("#velto-driver-dashboard"))return; const box=document.createElement("div");box.id="velto-driver-dashboard";box.className="glass-panel";box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><h1 style="margin:0">Tableau de bord livreur</h1><p class="subtitle">Gérez votre disponibilité, GPS et revenus.</p></div><span id="vd-online" class="vd-status">Hors ligne</span></div><div class="vd-grid"><div class="vd-stat"><span>Aujourd'hui</span><b id="vd-earnings">0,00 DT</b></div><div class="vd-stat"><span>Courses livrées</span><b id="vd-completed">0</b></div><div class="vd-stat"><span>Commission Velto</span><b id="vd-commission">0,00 DT</b></div><div class="vd-stat"><span>GPS</span><b id="vd-gps">Inactif</b></div></div><div class="vd-toolbar"><button id="vd-online-btn" class="vd-btn accent">Passer en ligne</button><button id="vd-gps-btn" class="vd-btn">Activer le GPS</button><button id="vd-refresh" class="vd-btn">Actualiser</button></div><div class="vd-two"><div><h2>Course active</h2><div id="vd-active"><p class="empty-state">Aucune course active.</p></div></div><div><h2>Position</h2><div id="vd-map" class="vd-map"></div></div></div>`;view.insertBefore(box,view.firstChild);bindDriver();}
  let driverMap=null, driverMarker=null;
  async function initMap(){if(driverMap)return; if(!window.L){await new Promise((res,rej)=>{const c=document.createElement("link");c.rel="stylesheet";c.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(c);const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=res;s.onerror=rej;document.head.appendChild(s)}).catch(()=>{});} if(!window.L||!$("#vd-map"))return;driverMap=L.map("vd-map").setView([36.8065,10.1815],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(driverMap);}
  async function setOnline(online){const r=await fetch(`${API}/drivers/me/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({isOnline:online,isAvailable:online})});const d=await json(r);if(!r.ok)throw Error(d.error||"Impossible de modifier le statut");state.user=d.user||state.user;renderOnline();}
  async function sendLocation(lat,lng){const r=await fetch(`${API}/drivers/me/location`,{method:"PATCH",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({lat,lng})});if(!r.ok)throw Error("GPS non enregistré");if(driverMap){const p=[lat,lng];if(!driverMarker)driverMarker=L.marker(p).addTo(driverMap).bindPopup("Ma position");else driverMarker.setLatLng(p);driverMap.setView(p,15);}}
  function startGps(){if(!navigator.geolocation)return toast("Votre navigateur ne supporte pas le GPS");if(state.gpsWatch!==null)return;state.gpsWatch=navigator.geolocation.watchPosition(async p=>{try{await sendLocation(p.coords.latitude,p.coords.longitude);$("#vd-gps").textContent="Actif";}catch(e){toast(e.message)}},()=>{toast("Autorisation GPS refusée")},{enableHighAccuracy:true,maximumAge:5000,timeout:10000});$("#vd-gps").textContent="Recherche…";initMap();}
  function renderOnline(){const on=!!state.user?.isOnline;$("#vd-online").textContent=on?(state.user?.isAvailable?"En ligne · disponible":"En ligne · occupé"):"Hors ligne";$("#vd-online-btn").textContent=on?"Passer hors ligne":"Passer en ligne";}
  async function loadDriver(){const r=await fetch(`${API}/orders`,{headers:headers()});const orders=await json(r);if(!Array.isArray(orders))return;const completed=orders.filter(o=>o.status==="livree");const earnings=completed.reduce((n,o)=>n+Number(o.driverEarnings||0),0);const commission=completed.reduce((n,o)=>n+Number(o.commission||0),0);$("#vd-earnings").textContent=earnings.toFixed(2)+" DT";$("#vd-completed").textContent=completed.length;$("#vd-commission").textContent=commission.toFixed(2)+" DT";const active=orders.find(o=>["acceptee","route"].includes(o.status));const host=$("#vd-active");if(!active){host.innerHTML='<p class="empty-state">Aucune course active.</p>';}else{host.innerHTML=`<div class="vd-row"><div><b>#${esc(String(active.id).slice(-5))}</b><div>${esc(active.pickup)} → ${esc(active.dropoff)}</div><span class="vd-muted">${esc(active.pkg)} · ${Number(active.driverEarnings||0).toFixed(2)} DT</span></div><div><span class="vd-status">${active.status}</span><div class="vd-toolbar">${active.status==="acceptee'?'<button class="vd-btn accent" id="vd-route">En route</button>':'<button class="vd-btn accent" id="vd-deliver">Livré</button>'}<button class="vd-btn" id="vd-cancel">Annuler</button></div></div></div>`;$("#vd-route")?.addEventListener("click",()=>status(active.id,"route"));$("#vd-deliver")?.addEventListener("click",()=>status(active.id,"livree"));$("#vd-cancel")?.addEventListener("click",()=>cancel(active.id));}
    const available=orders.filter(o=>o.status==="nouvelle"); if(available.length && !state.lastOrderIds.size){available.forEach(o=>state.lastOrderIds.add(o.id));} else {available.forEach(o=>{if(!state.lastOrderIds.has(o.id)){toast(`Nouvelle course : ${o.pickup} → ${o.dropoff}`);if("Notification"in window&&Notification.permission==="granted")new Notification("Velto · Nouvelle course",{body:`${o.pickup} → ${o.dropoff}`});state.lastOrderIds.add(o.id);}});}
    renderOnline(); await initMap();}
  async function status(id,status){const r=await fetch(`${API}/orders/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({status})});const d=await json(r);if(!r.ok)throw toast(d.error||"Action impossible");toast(status==="livree"?"Course livrée":"Course démarrée",true);loadDriver();}
  async function cancel(id){const reason=prompt("Raison de l'annulation","Indisponible")||"Annulée par le livreur";const r=await fetch(`${API}/orders/${id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({reason})});const d=await json(r);if(!r.ok)return toast(d.error||"Annulation impossible");toast("Course annulée",true);loadDriver();}
  function bindDriver(){$("#vd-online-btn").onclick=async()=>{try{await setOnline(!state.user.isOnline);toast(state.user.isOnline?"Vous êtes en ligne":"Vous êtes hors ligne",true);}catch(e){toast(e.message)}};$("#vd-gps-btn").onclick=()=>startGps();$("#vd-refresh").onclick=()=>loadDriver();}
  function ensureAdminUI(){if(state.user?.role!=="admin"||$("#view-admin"))return;const main=$("main");const s=document.createElement("section");s.id="view-admin";s.className="view";s.innerHTML=`<div class="glass-panel"><h1>Administration Velto</h1><p class="subtitle">Vue globale de la plateforme.</p><div class="vd-grid"><div class="vd-stat"><span>Utilisateurs</span><b id="ad-users">—</b></div><div class="vd-stat"><span>Livreurs en ligne</span><b id="ad-online">—</b></div><div class="vd-stat"><span>Commandes</span><b id="ad-orders">—</b></div><div class="vd-stat"><span>Commission</span><b id="ad-commission">—</b></div></div><div class="vd-toolbar"><button class="vd-btn active" data-filter="all">Toutes</button><button class="vd-btn" data-filter="nouvelle">Nouvelles</button><button class="vd-btn" data-filter="route">En route</button><button class="vd-btn" data-filter="livree">Livrées</button><button class="vd-btn" data-filter="annulee">Annulées</button></div><div id="ad-orders-list"></div></div>`;main.appendChild(s);s.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{s.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadAdmin(b.dataset.filter)});}
  async function loadAdmin(filter="all"){if(state.user?.role!=="admin")return;const [statsR,ordersR]=await Promise.all([fetch(`${API}/admin/stats`,{headers:headers()}),fetch(`${API}/admin/orders`,{headers:headers()})]);const stats=await json(statsR),orders=await json(ordersR);$("#ad-users").textContent=stats.users??stats.totalUsers??"—";$("#ad-online").textContent=stats.onlineDrivers??stats.onlineLivreurs??"—";$("#ad-orders").textContent=stats.orders??stats.totalOrders??(Array.isArray(orders)?orders.length:"—");$("#ad-commission").textContent=(Number(stats.commission??stats.totalCommission??0)||0).toFixed(2)+" DT";const list=Array.isArray(orders)?orders.filter(o=>filter==="all"||o.status===filter):[];$("#ad-orders-list").innerHTML=list.slice(0,50).map(o=>`<div class="vd-row"><div><b>#${esc(String(o.id).slice(-5))}</b> · ${esc(o.status)}<div>${esc(o.pickup)} → ${esc(o.dropoff)}</div></div><div><b>${Number(o.fee||0).toFixed(2)} DT</b><div class="vd-muted">${esc(o.client?.name||o.client||"")}</div></div></div>`).join("")||'<p class="empty-state">Aucune commande.</p>';}
  async function boot(){css();state.user=await me();if(!state.user)return;if(state.user.role==="livreur"){ensureDriverUI();loadDriver();setInterval(loadDriver,5000);}if(state.user.role==="admin"){ensureAdminUI();loadAdmin();setInterval(()=>loadAdmin(document.querySelector("#view-admin [data-filter].active")?.dataset.filter||"all"),7000);}}
  boot();window.addEventListener("storage",()=>boot());
})();
