(() => {
  const API = "https://wassel-backend-ds3n.onrender.com";
  const $ = s => document.querySelector(s);
  const state = { user:null, token:null, gps:null, map:null, marker:null, seen:new Set() };
  const headers = () => state.token ? {Authorization:`Bearer ${state.token}`} : {};
  const read = async r => { try{return await r.json()}catch{return {}} };
  const toast = msg => { let h=$("#vd-toast"); if(!h){h=document.createElement("div");h.id="vd-toast";h.style="position:fixed;right:20px;bottom:20px;z-index:99999";document.body.appendChild(h)} const x=document.createElement("div");x.textContent=msg;x.style="background:#211d18;color:#fff;padding:12px 16px;border-radius:14px;margin-top:8px;font:600 13px Inter";h.appendChild(x);setTimeout(()=>x.remove(),3500)};
  const esc = v => String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  function addCss(){if($("#vd-css"))return;const s=document.createElement("style");s.id="vd-css";s.textContent=`.vd-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:14px 0}.vd-stat{padding:15px;border:1px solid rgba(36,28,16,.1);border-radius:16px}.vd-stat span{font-size:12px;color:#857a67}.vd-stat b{display:block;font:800 24px Sora;margin-top:5px}.vd-tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.vd-btn{border:1px solid rgba(36,28,16,.12);border-radius:12px;padding:10px 13px;background:#fff;cursor:pointer;font-weight:700}.vd-btn.accent{background:#211d18;color:#fff}.vd-pill{padding:5px 9px;border-radius:99px;background:rgba(214,178,94,.18);font-size:12px;font-weight:700}.vd-row{display:flex;justify-content:space-between;gap:15px;align-items:center;padding:13px 0;border-bottom:1px solid rgba(36,28,16,.08)}.vd-row:last-child{border:0}.vd-map{height:250px;border-radius:16px;overflow:hidden;margin-top:10px}.vd-two{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}@media(max-width:800px){.vd-grid{grid-template-columns:repeat(2,1fr)}.vd-two{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  async function session(){state.token=localStorage.getItem("velto_token");if(!state.token)return null;const r=await fetch(`${API}/auth/me`,{headers:headers()}).catch(()=>null);if(!r?.ok)return null;return (await read(r)).user||null}
  async function leaflet(){if(window.L)return;await new Promise((ok,no)=>{const c=document.createElement("link");c.rel="stylesheet";c.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(c);const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=ok;s.onerror=no;document.head.appendChild(s)}).catch(()=>{})}
  async function driverMap(){await leaflet();if(!window.L||state.map||!$("#vd-map"))return;state.map=L.map("vd-map").setView([36.8065,10.1815],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(state.map)}
  function driverUI(){const v=$("#view-livreur");if(!v||$("#vd-dashboard"))return;const b=document.createElement("div");b.id="vd-dashboard";b.className="glass-panel";b.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><div><h1>Tableau de bord</h1><p class="subtitle">Gérez votre activité de livreur.</p></div><span id="vd-online" class="vd-pill">Hors ligne</span></div><div class="vd-grid"><div class="vd-stat"><span>Gains</span><b id="vd-earn">0 DT</b></div><div class="vd-stat"><span>Livraisons</span><b id="vd-done">0</b></div><div class="vd-stat"><span>Commission</span><b id="vd-comm">0 DT</b></div><div class="vd-stat"><span>GPS</span><b id="vd-gps">Off</b></div></div><div class="vd-tools"><button id="vd-online-btn" class="vd-btn accent">Passer en ligne</button><button id="vd-gps-btn" class="vd-btn">Activer GPS</button><button id="vd-refresh" class="vd-btn">Actualiser</button></div><div class="vd-two"><div><h2>Course active</h2><div id="vd-active"><p class="empty-state">Aucune course active.</p></div></div><div><h2>Ma position</h2><div id="vd-map" class="vd-map"></div></div></div>`;v.insertBefore(b,v.firstChild);$("#vd-online-btn").onclick=toggleOnline;$("#vd-gps-btn").onclick=startGps;$("#vd-refresh").onclick=loadDriver}
  async function toggleOnline(){const online=!state.user.isOnline;const r=await fetch(`${API}/drivers/me/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({isOnline:online,isAvailable:online})});const d=await read(r);if(!r.ok)return toast(d.error||"Action impossible");state.user=d.user||state.user;renderOnline();toast(online?"Vous êtes en ligne":"Vous êtes hors ligne")}
  function renderOnline(){const on=!!state.user?.isOnline;$("#vd-online").textContent=on?(state.user.isAvailable?"En ligne · disponible":"En ligne · occupé"):"Hors ligne";$("#vd-online-btn").textContent=on?"Passer hors ligne":"Passer en ligne"}
  function startGps(){if(!navigator.geolocation)return toast("GPS non supporté");if(state.gps!==null)return toast("GPS déjà actif");state.gps=navigator.geolocation.watchPosition(async p=>{const {latitude:lat,longitude:lng}=p.coords;const r=await fetch(`${API}/drivers/me/location`,{method:"PATCH",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({lat,lng})});if(r.ok){$("#vd-gps").textContent="Actif";await driverMap();if(state.map){const q=[lat,lng];if(!state.marker)state.marker=L.marker(q).addTo(state.map).bindPopup("Ma position");else state.marker.setLatLng(q);state.map.setView(q,15)}}},()=>toast("Autorisation GPS refusée"),{enableHighAccuracy:true,maximumAge:5000,timeout:10000});$("#vd-gps").textContent="Recherche…"}
  async function change(id,status){const r=await fetch(`${API}/orders/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({status})});const d=await read(r);if(!r.ok)return toast(d.error||"Action impossible");toast(status==="livree"?"Commande livrée":"Course démarrée");loadDriver()}
  async function cancel(id){const reason=prompt("Raison de l'annulation","Indisponible")||"Annulée par le livreur";const r=await fetch(`${API}/orders/${id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({reason})});const d=await read(r);if(!r.ok)return toast(d.error||"Annulation impossible");toast("Commande annulée");loadDriver()}
  async function loadDriver(){if(state.user?.role!=="livreur")return;const r=await fetch(`${API}/orders`,{headers:headers()});const orders=await read(r);if(!Array.isArray(orders))return;const done=orders.filter(o=>o.status==="livree");$("#vd-earn").textContent=done.reduce((n,o)=>n+Number(o.driverEarnings||0),0).toFixed(2)+" DT";$("#vd-done").textContent=done.length;$("#vd-comm").textContent=done.reduce((n,o)=>n+Number(o.commission||0),0).toFixed(2)+" DT";const active=orders.find(o=>["acceptee","route"].includes(o.status));const h=$("#vd-active");if(!active)h.innerHTML='<p class="empty-state">Aucune course active.</p>';else{h.innerHTML=`<div class="vd-row"><div><b>#${esc(String(active.id).slice(-5))}</b><div>${esc(active.pickup)} → ${esc(active.dropoff)}</div><small>${esc(active.pkg)} · ${Number(active.driverEarnings||0).toFixed(2)} DT</small></div><div><span class="vd-pill">${esc(active.status)}</span><div class="vd-tools">${active.status==="acceptee'?"":""}</div></div></div>`;const tools=h.querySelector(".vd-tools");const btn=document.createElement("button");btn.className="vd-btn accent";btn.textContent=active.status==="acceptee"?"En route":"Livré";btn.onclick=()=>change(active.id,active.status==="acceptee"?"route":"livree");tools.appendChild(btn);const c=document.createElement("button");c.className="vd-btn";c.textContent="Annuler";c.onclick=()=>cancel(active.id);tools.appendChild(c)}renderOnline();await driverMap();const fresh=orders.filter(o=>o.status==="nouvelle");fresh.forEach(o=>{if(!state.seen.has(o.id)){if(state.seen.size)toast(`Nouvelle course : ${o.pickup} → ${o.dropoff}`);state.seen.add(o.id)}})}
  async function adminUI(){if(state.user?.role!=="admin"||$("#view-admin"))return;const s=document.createElement("section");s.id="view-admin";s.className="view";s.innerHTML=`<div class="glass-panel"><h1>Administration</h1><p class="subtitle">Suivi global de Velto.</p><div class="vd-grid"><div class="vd-stat"><span>Utilisateurs</span><b id="ad-users">—</b></div><div class="vd-stat"><span>Livreurs en ligne</span><b id="ad-online">—</b></div><div class="vd-stat"><span>Commandes</span><b id="ad-orders">—</b></div><div class="vd-stat"><span>Commission</span><b id="ad-comm">—</b></div></div><div class="vd-tools"><button class="vd-btn active" data-f="all">Toutes</button><button class="vd-btn" data-f="nouvelle">Nouvelles</button><button class="vd-btn" data-f="route">En route</button><button class="vd-btn" data-f="livree">Livrées</button><button class="vd-btn" data-f="annulee">Annulées</button></div><div id="ad-list"></div></div>`;$("main").appendChild(s);s.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{s.querySelectorAll("[data-f]").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadAdmin(b.dataset.f)})}
  async function loadAdmin(filter="all"){if(state.user?.role!=="admin")return;const [a,b]=await Promise.all([fetch(`${API}/admin/stats`,{headers:headers()}),fetch(`${API}/admin/orders`,{headers:headers()})]);const st=await read(a),os=await read(b);$("#ad-users").textContent=st.users??st.totalUsers??"—";$("#ad-online").textContent=st.onlineDrivers??st.onlineLivreurs??"—";const list=Array.isArray(os)?os.filter(o=>filter==="all"||o.status===filter):[];$("#ad-orders").textContent=st.orders??st.totalOrders??list.length;$("#ad-comm").textContent=(Number(st.commission??st.totalCommission??0)).toFixed(2)+" DT";$("#ad-list").innerHTML=list.slice(0,50).map(o=>`<div class="vd-row"><div><b>#${esc(String(o.id).slice(-5))}</b> · ${esc(o.status)}<div>${esc(o.pickup)} → ${esc(o.dropoff)}</div></div><b>${Number(o.fee||0).toFixed(2)} DT</b></div>`).join("")||'<p class="empty-state">Aucune commande.</p>'}
  async function boot(){addCss();state.user=await session();if(!state.user)return;if(state.user.role==="livreur"){driverUI();loadDriver();setInterval(loadDriver,5000)}if(state.user.role==="admin"){await adminUI();loadAdmin();setInterval(()=>loadAdmin($("#view-admin [data-f].active")?.dataset.f||"all"),7000)}}
  boot();
})();
