(()=>{
const API="https://wassel-backend-ds3n.onrender.com";
const token=()=>localStorage.getItem("velto_token")||"";
const H=()=>token()?{Authorization:`Bearer ${token()}`}:{ };
const J=async r=>{try{return await r.json()}catch{return{}}};
let user=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const typeInfo={colis:["📦","Colis"],food:["🍔","Food"],taxi:["🚗","Taxi"],shop:["🛍️","Shop"],market:["🛒","Market"]};
function typeOf(o){const m=String(o.pkg||"").match(/^\[(COLIS|FOOD|TAXI|SHOP|MARKET)\]/i);return m?m[1].toLowerCase():"colis"}
function toast(m){let x=$("#d2toast");if(!x){x=document.createElement("div");x.id="d2toast";x.style="position:fixed;right:20px;bottom:20px;z-index:100000;background:#211d18;color:#fff;padding:13px 17px;border-radius:13px;font:600 13px Inter,Arial;box-shadow:0 12px 35px rgba(0,0,0,.2)";document.body.append(x)}x.textContent=m;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),3200)}
function styles(){if($("#d2style"))return;const s=document.createElement("style");s.id="d2style";s.textContent=`.d2grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:15px 0}.d2stat{padding:15px;border:1px solid rgba(36,28,16,.1);border-radius:15px;background:rgba(255,255,255,.35)}.d2stat small{color:#857a67}.d2stat b{display:block;font-size:23px;margin-top:5px}.d2tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.d2btn{padding:10px 14px;border-radius:11px;border:1px solid #ddd;background:white;font-weight:700;cursor:pointer}.d2primary{background:#211d18;color:white}.d2row{display:flex;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid #eee}.d2type{display:inline-flex;align-items:center;gap:5px;padding:4px 8px;border-radius:99px;background:#f3eee6;font-size:12px;font-weight:700}.d2filter{padding:8px 11px;border:1px solid #ddd;border-radius:10px;background:white;font-weight:700;cursor:pointer}.d2filter.active{background:#211d18;color:#fff}.d2map{height:250px;border-radius:15px;overflow:hidden}#view-livreur #available-orders,#view-livreur #my-deliveries{display:none!important}@media(max-width:800px){.d2grid{grid-template-columns:repeat(2,1fr)}.d2row{flex-direction:column}}`;document.head.append(s)}
async function me(){const t=token();if(!t)return;const r=await fetch(API+"/auth/me",{headers:H()}).catch(()=>null);if(r?.ok)user=(await J(r)).user}
async function driver(){const v=$("#view-livreur");if(!v||$("#d2driver"))return;const b=document.createElement("div");b.id="d2driver";b.className="glass-panel";b.innerHTML=`<h1>Tableau de bord livreur</h1><p class="subtitle">Gérez vos courses, votre disponibilité et votre position GPS.</p><div class="d2grid"><div class="d2stat"><small>Gains</small><b id="d2earn">0 DT</b></div><div class="d2stat"><small>Livraisons</small><b id="d2done">0</b></div><div class="d2stat"><small>Commandes actives</small><b id="d2activeCount">0</b></div><div class="d2stat"><small>GPS</small><b id="d2gps">Off</b></div></div><div class="d2tools"><button id="d2online" class="d2btn d2primary"></button><button id="d2gpsbtn" class="d2btn">Activer GPS</button></div><div class="d2tools" id="d2filters"><button class="d2filter active" data-f="all">Toutes</button><button class="d2filter" data-f="colis">📦 Colis</button><button class="d2filter" data-f="food">🍔 Food</button><button class="d2filter" data-f="taxi">🚗 Taxi</button><button class="d2filter" data-f="shop">🛍️ Shop</button><button class="d2filter" data-f="market">🛒 Market</button></div><div class="d2row"><div style="flex:1"><h2>Courses disponibles</h2><div id="d2available">Aucune nouvelle course.</div><h2 style="margin-top:22px">Course active</h2><div id="d2active">Aucune course active.</div></div><div style="width:42%"><h2>Position</h2><div id="d2map" class="d2map"></div></div></div><h2 style="margin-top:22px">Historique des courses</h2><div id="d2history"></div>`;
v.prepend(b);
$("#d2online").onclick=async()=>{const on=!user?.isOnline;const r=await fetch(API+"/drivers/me/status",{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({isOnline:on,isAvailable:on})});const d=await J(r);if(r.ok){user=d.user||user;renderOnline()}else toast(d.error||"Erreur")};
$("#d2filters").onclick=e=>{const btn=e.target.closest("[data-f]");if(!btn)return;document.querySelectorAll("#d2filters .d2filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");loadDriver(btn.dataset.f)};
renderOnline();loadDriver("all");setInterval(()=>loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all"),5000)}
function renderOnline(){if($("#d2online"))$("#d2online").textContent=user?.isOnline?"Passer hors ligne":"Passer en ligne"}
async function loadDriver(filter="all"){if(user?.role!=="livreur")return;const r=await fetch(API+"/orders",{headers:H()});const os=await J(r);if(!Array.isArray(os))return;const done=os.filter(o=>o.status==="livree");$("#d2earn").textContent=done.reduce((n,o)=>n+Number(o.driverEarnings||0),0).toFixed(2)+" DT";$("#d2done").textContent=done.length;const active=os.filter(o=>["acceptee","route"].includes(o.status));$("#d2activeCount").textContent=active.length;const available=os.filter(o=>o.status==="nouvelle");renderAvailable(filter==="all"?available:available.filter(o=>typeOf(o)===filter));renderActive(active.filter(o=>filter==="all"||typeOf(o)===filter));const shown=filter==="all"?os:os.filter(o=>typeOf(o)===filter);renderHistory(shown.filter(o=>o.status==="livree"||o.status==="annulee"));}
function badge(o){const [i,n]=typeInfo[typeOf(o)]||typeInfo.colis;return `<span class="d2type">${i} ${n}</span>`}
function renderAvailable(list){const h=$("#d2available");if(!h)return;if(!list.length){h.innerHTML='<p class="empty-state">Aucune nouvelle course disponible.</p>';return}h.innerHTML=list.slice(0,20).map(a=>`<div style="padding-bottom:14px"><div>${badge(a)} <b>#${esc(String(a.id).slice(-5))}</b></div><p style="margin:9px 0">${esc(a.pickup)} → ${esc(a.dropoff)}</p><small>${esc(a.pkg)} · <b>${Number(a.fee||0).toFixed(2)} DT</b></small><div class="d2tools"><button class="d2btn d2primary" data-action="accept" data-id="${esc(a.id)}">Accepter la course</button></div></div>`).join("");h.onclick=e=>{const b=e.target.closest("[data-action]");if(b&&b.dataset.action==="accept")change(b.dataset.id,"acceptee")}}
function renderActive(active){const h=$("#d2active");if(!active.length){h.textContent="Aucune course active.";return}h.innerHTML=active.map(a=>`<div style="padding-bottom:14px"><div>${badge(a)} <b>#${esc(String(a.id).slice(-5))}</b></div><p style="margin:9px 0">${esc(a.pickup)} → ${esc(a.dropoff)}</p><small>${esc(a.pkg)} · <b>${Number(a.driverEarnings||0).toFixed(2)} DT</b></small><div class="d2tools"><button class="d2btn d2primary" data-action="${a.status==='acceptee'?'route':'livree'}" data-id="${esc(a.id)}">${a.status==='acceptee'?"En route":"Livré"}</button><button class="d2btn" data-action="cancel" data-id="${esc(a.id)}">Annuler</button></div></div>`).join("");h.onclick=e=>{const b=e.target.closest("[data-action]");if(b)b.dataset.action==="cancel"?cancel(b.dataset.id):change(b.dataset.id,b.dataset.action)} }
function renderHistory(list){const h=$("#d2history");if(!list.length){h.innerHTML='<p class="empty-state">Aucun historique pour ce filtre.</p>';return}h.innerHTML=list.slice(0,30).map(o=>`<div class="d2row"><span>${badge(o)} <b>#${esc(String(o.id).slice(-5))}</b><br><small>${esc(o.pickup)} → ${esc(o.dropoff)}</small></span><b>${Number(o.driverEarnings||0).toFixed(2)} DT</b></div>`).join("")}
async function change(id,status){const r=await fetch(API+`/orders/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({status})});const d=await J(r);if(!r.ok)return toast(d.error||"Erreur");toast(status==="acceptee"?"Course acceptée":status==="livree"?"Course livrée":"Course démarrée");loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all")}
async function cancel(id){const reason=prompt("Raison de l'annulation","Indisponible")||"Annulée par le livreur";const r=await fetch(API+`/orders/${id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({reason})});const d=await J(r);if(!r.ok)return toast(d.error||"Erreur");toast("Commande annulée");loadDriver(document.querySelector("#d2filters .active")?.dataset.f||"all")}
async function startGPS(){if(!navigator.geolocation)return toast("GPS non supporté");if(window.__veltoGpsWatch)return toast("GPS déjà actif");window.__veltoGpsWatch=navigator.geolocation.watchPosition(async p=>{const lat=p.coords.latitude,lng=p.coords.longitude;const r=await fetch(API+"/drivers/me/location",{method:"PATCH",headers:{"Content-Type":"application/json",...H()},body:JSON.stringify({lat,lng})});if(r.ok)$("#d2gps").textContent="Actif"},()=>toast("Autorisation GPS refusée"),{enableHighAccuracy:true,maximumAge:5000,timeout:10000});toast("GPS activé")}
async function admin(){if(user?.role!=="admin"||$("#d2admin"))return;const s=document.createElement("section");s.id="d2admin";s.className="view";s.innerHTML=`<div class="glass-panel"><h1>Administration Velto</h1><div class="d2grid"><div class="d2stat"><small>Utilisateurs</small><b id="ausers">—</b></div><div class="d2stat"><small>Commandes</small><b id="aorders">—</b></div><div class="d2stat"><small>Livreurs en ligne</small><b id="aonline">—</b></div><div class="d2stat"><small>Commission</small><b id="acomm">—</b></div></div><div class="d2tools"><button class="d2filter active" data-af="all">Toutes</button><button class="d2filter" data-af="nouvelle">Nouvelles</button><button class="d2filter" data-af="acceptee">Acceptées</button><button class="d2filter" data-af="route">En route</button><button class="d2filter" data-af="livree">Livrées</button><button class="d2filter" data-af="annulee">Annulées</button></div><div id="alist"></div></div>`;$("main").append(s);s.onclick=e=>{const b=e.target.closest("[data-af]");if(!b)return;s.querySelectorAll("[data-af]").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadAdmin(b.dataset.af)};loadAdmin("all");setInterval(()=>loadAdmin(s.querySelector("[data-af].active")?.dataset.af||"all"),7000)}
async function loadAdmin(filter){if(user?.role!=="admin")return;const [a,b]=await Promise.all([fetch(API+"/admin/stats",{headers:H()}),fetch(API+"/orders",{headers:H()})]);const st=await J(a),os=await J(b);$("#ausers").textContent=st.users??st.totalUsers??"—";$("#aorders").textContent=st.orders??st.totalOrders??(Array.isArray(os)?os.length:"—");$("#aonline").textContent=st.onlineDrivers??st.onlineLivreurs??"—";$("#acomm").textContent=Number(st.commission??st.totalCommission??0).toFixed(2)+" DT";const list=Array.isArray(os)?(filter==="all"?os:os.filter(o=>o.status===filter)):[];$("#alist").innerHTML=list.slice(0,50).map(o=>`<div class="d2row"><span>${badge(o)} <b>#${esc(String(o.id).slice(-5))}</b><br>${esc(o.pickup)} → ${esc(o.dropoff)}<br><small>${esc(o.status)} · ${esc(o.pkg)}</small></span><b>${Number(o.fee||0).toFixed(2)} DT</b></div>`).join("")||'<p class="empty-state">Aucune commande.</p>'}
async function boot(){styles();await me();if(user?.role==="livreur")driver();if(user?.role==="admin")admin()}
boot();
})();