(()=>{
const API="https://wassel-backend-ds3n.onrender.com";
const token=()=>localStorage.getItem("velto_token")||"";
const H=()=>token()?{Authorization:`Bearer ${token()}`}:{ };
const J=async r=>{try{return await r.json()}catch{return{}}};
let map=null,driverMarker=null,routeLine=null,pickupMarker=null,dropoffMarker=null,gpsWatch=null,lastOrders="";
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.append(css);const js=document.createElement("script");js.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";js.onload=resolve;js.onerror=reject;document.head.append(js)})}
function styles(){if($("#dmapstyle"))return;const s=document.createElement("style");s.id="dmapstyle";s.textContent=`#d2map{min-height:320px;background:#eee}.dmap-controls{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.dmap-btn{border:1px solid #ddd;background:#fff;border-radius:10px;padding:8px 10px;font-weight:700;cursor:pointer}.dmap-live{font-size:12px;font-weight:800;padding:7px 10px;border-radius:99px;background:#edf8ef;color:#26733a}.dmap-nav{display:none}`;document.head.append(s)}
function init(){const el=$("#d2map");if(!el||map)return;map=L.map(el,{zoomControl:true}).setView([36.8065,10.1815],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);const controls=document.createElement("div");controls.className="dmap-controls";controls.innerHTML=`<span id="dmapLive" class="dmap-live">● GPS en attente</span><button id="dmapCenter" class="dmap-btn">◎ Ma position</button><button id="dmapNav" class="dmap-btn dmap-nav">🧭 Naviguer vers le retrait</button>`;el.parentElement?.append(controls);$("#dmapCenter").onclick=()=>{if(driverMarker)map.setView(driverMarker.getLatLng(),15);else startGPS()};$("#dmapNav").onclick=()=>{const o=window.__veltoMapOrder;if(!o?.pickupLocation)return;const p=o.pickupLocation;window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${p.lat},${p.lng}`)}`,'_blank','noopener')};map.invalidateSize()}
function setDriver(lat,lng){if(!map)return;const pos=[lat,lng];if(!driverMarker){driverMarker=L.marker(pos).addTo(map).bindPopup("<b>Vous</b><br>Position en direct")}else driverMarker.setLatLng(pos);$("#dmapLive")?.replaceChildren(document.createTextNode("● GPS actif"));if(!window.__veltoMapCentered){map.setView(pos,14);window.__veltoMapCentered=true}}
function markerIcon(emoji){return L.divIcon({className:"",html:`<div style="font-size:27px;filter:drop-shadow(0 2px 3px rgba(0,0,0,.25))">${emoji}</div>`,iconSize:[30,30],iconAnchor:[15,15]})}
function renderOrder(o){if(!map)return;window.__veltoMapOrder=o||null;[pickupMarker,dropoffMarker,routeLine].forEach(x=>x&&map.removeLayer(x));pickupMarker=dropoffMarker=routeLine=null;const p=o?.pickupLocation,d=o?.dropoffLocation;if(!p||!d||!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lng))||!Number.isFinite(Number(d.lat))||!Number.isFinite(Number(d.lng))){$("#dmapNav")?.style.setProperty("display","none");return}pickupMarker=L.marker([p.lat,p.lng],{icon:markerIcon("📍")}).addTo(map).bindPopup(`<b>Retrait</b><br>${esc(o.pickup)}`);dropoffMarker=L.marker([d.lat,d.lng],{icon:markerIcon("🏁")}).addTo(map).bindPopup(`<b>Livraison</b><br>${esc(o.dropoff)}`);routeLine=L.polyline([[p.lat,p.lng],[d.lat,d.lng]],{weight:5,dashArray:"10 8"}).addTo(map);$("#dmapNav")?.style.setProperty("display","inline-block");const group=L.featureGroup([pickupMarker,dropoffMarker,driverMarker].filter(Boolean));map.fitBounds(group.getBounds().pad(.25),{maxZoom:15})}
async function pollOrder(){const r=await fetch(API+"/orders",{headers:H()}).catch(()=>null);if(!r?.ok)return;const os=await J(r);if(!Array.isArray(os))return;const active=os.find(o=>["acceptee","route"].includes(o.status));const key=active?`${active.id}:${active.status}:${active.pickupLocation?.lat}:${active.dropoffLocation?.lat}`:"none";if(key!==lastOrders){lastOrders=key;renderOrder(active)}}
function startGPS(){if(gpsWatch||!navigator.geolocation)return;if(!window.isSecureContext&&location.hostname!=="localhost")return;gpsWatch=navigator.geolocation.watchPosition(p=>setDriver(p.coords.latitude,p.coords.longitude),()=>{$("#dmapLive")?.replaceChildren(document.createTextNode("● GPS refusé"))},{enableHighAccuracy:true,maximumAge:3000,timeout:10000})}
async function boot(){styles();try{await loadLeaflet()}catch{return}const wait=setInterval(()=>{if($("#d2map")){clearInterval(wait);init();startGPS();pollOrder();setInterval(pollOrder,5000)}},100)}
setTimeout(boot,0);
})();
